index.bs
index.html

Uses `StructuredSerialize`, which doesn't allow transfer but is simple.
Resolves #28.

Allow passing structured cloneable data to HTMLPortalElement/activate

---

w3c.json

Per https://w3c.github.io/w3c.json.html, the group value should be a number or array of numbers, and the repo-type value should be a quoted string.

Fix w3c.json syntax.

---

index.bs

These links should be updated to reflect the repository move. LGTY?

Update self-links to point at WICG/portals.

---

index.bs

We should not allow such things to be activated (if you're in an iframe, you cannot take over the main frame), and the simplest way to do so is to not allow them to exist in the first place. If we later change our mind it would be easy enough to move this check to activation. This is the more conservative approach.
It is easy enough for a page to know that it is in a nested browsing context (checking `window.parent`), and there's unfortunately not a natural way to report this error in the API, so I've included non-normative text suggesting a developer warning.

Disallow creating a portal browsing context inside a nested browsing context.

---

index.bs

This is an interesting feature that Bikeshed has that might prove useful. You can annotate the spec sections with the corresponding tests and so identify sections of the spec that aren't well covered (or so the theory goes). I've put it in inline display mode (where it actually renders a list of the tests with links to the source and a live version), but it can also be put in a mode where it doesn't render anything.
It does, however, generate errors if there are WPT tests that aren't listed in the spec (the idea being that the spec editors should be update for new WPT tests shortly thereafter). I'm not sure how I feel about that, but maybe it's worth a shot.

Annotate portals spec with links to corresponding WPT.

---

index.bs

The question of what the host and guest event loops know about each other during `postMessage` came up when talking with @a4sriniv. This is one take, but review closely as I'm not certain whether these are the ideal semantics.

Clarify the preconditions around postMessage between a portal contents and its host.

---

index.bs

Ordering is guaranteed between tasks queued to the same `(task source, event loop)` tuple, if they were sequenced to begin with. I think this suffices to give us the ordering guarantees we want but is still flexible enough.
`MessagePort` is more flexible insofar as it has one task source per port object, but I don't think we require that flexibility, and having it makes it harder to figure out how to make the desired guarantees between `activate`, `postMessage` and `adoptPredecessor`.
WDYT, @lucasgadani and @a4sriniv?

Define a portal task source and use it for all portal-related tasks.

---

index.bs

I couldn't think of a way to explicitly capture the state where the UA tries to render while portal has lost its guest browsing context but before swapping, so I ended up just going for wording that UAs should do what they can to avoid this (the Chromium compositing path seems to make this possible, but it's hard to know what would be required in other UAs, especially since the timing of this sort of thing doesn't seem to be speced in detail).

Clear the guest browsing context of a <portal> during activate.

---

index.bs

The Exposed attribute is now mandatory.
Resolves #73.

Add [Exposed=Window] to WebIDL interfaces.

---

index.bs

Remove use of 'context object' from dom.spec.whatwg.org.

---

index.bs

Hopefully this explains how the adopting steps prevent you from embedding a portal inside an <iframe>.
Resolves #82.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/103.html" title="Last updated on Apr 25, 2019, 3:21 PM UTC (ca61ba4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/103/9766d82...jeremyroman:ca61ba4.html" title="Last updated on Apr 25, 2019, 3:21 PM UTC (ca61ba4)">Diff</a>

Clarify no-portals-in-subframes note.

---

index.bs

Resolves #72.
Resolves #79.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/104.html" title="Last updated on Apr 25, 2019, 3:44 PM UTC (01dc7cf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/104/18b9d1e...jeremyroman:01dc7cf.html" title="Last updated on Apr 25, 2019, 3:44 PM UTC (01dc7cf)">Diff</a>

Correct HTMLPortalElement src IDL and content attribute wording.

---

demos/portal-embed-demo/README.md
demos/portal-embed-demo/public/js/portalog/portals-controller.js

Fixing bugs
- Removing "When the promise resolves, it means the page was adopted as a predecessor" comment from README.md (degradation)
- Changing using `append` from `appendChild` for adding fallback elements when the browser does not support Portals. The current implementation is using `appendChild` with multiple nodes as a parameter but it should be `append` in order to do that.
- Checked other places using `appendChild` to see similar bugs. This one was the only one.

Fixing bugs (README.md and protals-controller.js)

---

index.bs

Resolves #128.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/129.html" title="Last updated on May 16, 2019, 8:33 PM UTC (f85ac56)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/129/951367a...jeremyroman:f85ac56.html" title="Last updated on May 16, 2019, 8:33 PM UTC (f85ac56)">Diff</a>

Only allow setting src on a portal to an HTTP(S) URL.

---

index.bs

@a4sriniv PTAL
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/126.html" title="Last updated on May 16, 2019, 8:44 PM UTC (d3cd8de)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/126/951367a...jeremyroman:d3cd8de.html" title="Last updated on May 16, 2019, 8:44 PM UTC (d3cd8de)">Diff</a>

Fix ordering to permit postMessage immediately after adoptPredecessor.

---

index.bs

Resolves #81. There's more to do as far as updating things to use new things like agents and browsing context groups pervasively, but this is a fairly simple targeted fix.
@domenic?
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/130.html" title="Last updated on May 16, 2019, 9:24 PM UTC (fc5bb68)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/130/665046f...jeremyroman:fc5bb68.html" title="Last updated on May 16, 2019, 9:24 PM UTC (fc5bb68)">Diff</a>

Use the new 'create a new top-level browsing context' abstraction.

---

index.bs

Resolves #87 by simply assuming that the only type of host is `HTMLPortalElement`. In particular this allows `PortalHost/postMessage` to be one contiguous block.
We can unwind this if we ever do care about some other kind of host environment.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/127.html" title="Last updated on May 17, 2019, 8:19 PM UTC (e77e9ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/127/665046f...jeremyroman:e77e9ea.html" title="Last updated on May 17, 2019, 8:19 PM UTC (e77e9ea)">Diff</a>

Remove host abstraction

---

index.bs

Resolves #76.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/132.html" title="Last updated on May 24, 2019, 3:26 PM UTC (b87e976)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/132/2195b2d...jeremyroman:b87e976.html" title="Last updated on May 24, 2019, 3:26 PM UTC (b87e976)">Diff</a>

Consistently refer to the guest browsing context as either a browsing context or null.

---

index.bs

Resolves #68, and attempts to be consistent with iframes by not filing the unload family of events in the event that the context is to be discarded due to removal from the DOM (as opposed to navigation to an empty URL or activation).
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/131.html" title="Last updated on May 24, 2019, 3:38 PM UTC (7819875)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/131/cebe701...jeremyroman:7819875.html" title="Last updated on May 24, 2019, 3:38 PM UTC (7819875)">Diff</a>

Adjust behavior around closing and discarding guest browsing contexts.

---

index.bs

Resolves #63.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/135.html" title="Last updated on May 24, 2019, 6:31 PM UTC (e702e87)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/135/d297d7d...jeremyroman:e702e87.html" title="Last updated on May 24, 2019, 6:31 PM UTC (e702e87)">Diff</a>

Remove note that repeats that portal browsing contexts are top-level.

---

index.bs

Resolves #140.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/141.html" title="Last updated on May 30, 2019, 8:57 PM UTC (4e24cd6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/141/8070b25...jeremyroman:4e24cd6.html" title="Last updated on May 30, 2019, 8:57 PM UTC (4e24cd6)">Diff</a>

Replace the term 'unit of related browsing contexts', which is deprecated.

---

index.bs

Resolves #137.
PTAL and let me know if you agree that this is the right behavior.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/138.html" title="Last updated on Jun 20, 2019, 8:39 PM UTC (cc1abcb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/138/61494cd...jeremyroman:cc1abcb.html" title="Last updated on Jun 20, 2019, 8:39 PM UTC (cc1abcb)">Diff</a>

Tie BC creation to availability of a valid src + BC connectedness.

---

index.bs

This is my attempt to start monkey-patching in the integrations with CSP and similar webappsec specs.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/159.html" title="Last updated on Sep 20, 2019, 8:56 AM UTC (e9ad659)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/159/efd7ba3...jeremyroman:e9ad659.html" title="Last updated on Sep 20, 2019, 8:56 AM UTC (e9ad659)">Diff</a>

Specify how Portals integrates with webappsec specifications.

---

index.bs

Fixes #170.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/171.html" title="Last updated on Jan 15, 2020, 7:42 PM UTC (bbc382a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/171/9fdc1de...jeremyroman:bbc382a.html" title="Last updated on Jan 15, 2020, 7:42 PM UTC (bbc382a)">Diff</a>

Fix references to HTML spec that should have been definition autolinks.

---

index.bs

This brings the spec closer to how it would look upon landing in HTML, and explicitly calls out what sections it would expect things to land in. Notable changes:
* Moved window.portalHost from "Miscellaneous extensions" into a new "Portal hosts" section, which contains the definitions for both window.portalHost and the PortalHost interface.
* Made the onportalactivate event handler addition match HTML's existing structure.
* Moved subsections of "Security considerations" which were spec patches into a new dedicated section, "Updates to other specifications".
* Noted the connection to whatwg/html#1230 in addition to RFC 7034.
* Tweaks the wording in the "Fetch Metadata Request Headers" section's non-normative summary notes.
***
<a …

Rearrange spec structure as more explicit patches

---

README.md

In particular this change addresses topics discussed in #193.

Add some information about portal rendering to the explainer.

---

index.bs

The normative change here is that by default data is undefined instead of null. Closes #74.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/204.html" title="Last updated on May 20, 2020, 8:52 PM UTC (cbfeef7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/204/7200658...cbfeef7.html" title="Last updated on May 20, 2020, 8:52 PM UTC (cbfeef7)">Diff</a>

Tweak PortalActivateOptions IDL

---

index.bs

Part of #26. This does not yet take care of delaying the load event of the outer window.
Some things to note:
- Iframes have an "iframe load in progress" flag which is [set before and unset after firing the event](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#iframe-load-event-steps). I guess this is to prevent a sort of infinite recursion? This didn't seem very necessary so I didn't copy it, but I might be wrong.
- Iframes have a "mute iframe load" flag which is set by document.open(), and has some known spec bugs. This seems like legacy so we shouldn't copy it, I'm pretty sure.
Please let me know what you think of these points, as well as how well this matches the Chromium implementation.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/206.html" …

Fire the load event for portals

---

index.bs

Closes #196.
Things to discuss before merging:
- I've currently located the checks inside the posted tasks.
- I am unsure whether this is necessary; could the origin change between the task being posted and it being run? Wouldn't we only run the task if the document was active, and thus the origin would have stay the same?
- However, checking in the posted task matches the current targetOrigin check done in HTML, so maybe there's a good reason?
- Even if it is necessary, should we consider also doing the check before posting the task? That seems slightly more developer-friendly.
- I've removed the non-options overloads for postMessage(), i.e. #205. That is, I kept `postMessage(data, { transfer })`, but removed `postMessage(data, transfer)`. We could keep both if we preferred, but I prefer …

Remove cross-origin postMessage()ing

---

README.md
index.bs

Resolves #174.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/223.html" title="Last updated on Jul 7, 2020, 5:21 PM UTC (533c846)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/223/7e745af...jeremyroman:533c846.html" title="Last updated on Jul 7, 2020, 5:21 PM UTC (533c846)">Diff</a>

Define the activation behavior of a <portal> element.

---

README.md

The first example in the explainer uses www.example.com and
example.com interchangeably. We now just use example.com for
consistency, since these are technically different origins.

Consistently refer to example.com in the explainer

---

Makefile
index.bs

This also switches to "explicit for" mode in Bikeshed, which changes our link syntax a bit.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/245.html" title="Last updated on Aug 25, 2020, 5:48 PM UTC (2d70887)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/245/5df9f8d...2d70887.html" title="Last updated on Aug 25, 2020, 5:48 PM UTC (2d70887)">Diff</a>

Meta: get the spec building without warnings

---

index.bs

Closes #243.
Note: this specifies that portals in the state "orphaned" are also not closable. I don't believe we have tests for that, but we should, IMO.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/246.html" title="Last updated on Aug 26, 2020, 6:17 PM UTC (49a8aef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/246/863124f...49a8aef.html" title="Last updated on Aug 26, 2020, 6:17 PM UTC (49a8aef)">Diff</a>

Specify window.close() to no-op in unactivated portals

---

README.md
index.bs

Closes #240. Closes #232.
Although the discussion isn't fully settled, I thought it would be good to write up some spec text at least, and put an initial stake in the ground.
I looked into speccing navigate-to and decided that how it works is highly dependent on [how we spec navigating portals](https://docs.google.com/document/d/10qKRyACKBo8mSYgIgcuHQLuwNkmPtI-NIoEl6oizc8A/edit?ts=5f0c642b), so I left it un-specced for now.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/249.html" title="Last updated on Sep 3, 2020, 9:30 PM UTC (20ce690)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/249/535ef86...20ce690.html" title="Last updated on Sep 3, 2020, 9:30 PM UTC (20ce690)">Diff</a>

Update CSP explainer/spec and expand on the opt-in

---

index.bs

Closes #145.
Test cases this should generate:
- For each `badURL` of `data:text/html,foo`, `javascript:'a string'`, `javascript:undefined`, `about:blank`, a `blob:` URL, and a real URL that is served with the `Content-Disposition: attachment` header, a real URL that has a 204 response, and a real URL that has a 205 response:
- `<portal src="badURL"></portal>` must end up closed
- `<portal src="redirect"></portal>` where `redirect` redirects (say, 302) to `badURL` must end up closed
- `<portal src="web+test:foo"></portal>` where `web+test` is mapped using `registerProtocolHandler` to `badURL` must end up closed. (Only possible for same-origin HTTPS bad URLs; you can't register the others.)
- `<portal src="test"></portal>` where `test` does `location.href = badURL` must stay on `test` and …

Prevent navigations to non-HTTP(S) URLs

---

README.md
index.bs

Closes #197 by causing all changes to `src=""` to close the portal browsing context, and re-create it.
Closes #227 by causing `activate()` to delay promise resolution/rejection until the initial load in a new browsing context has finished.
<details>
<summary>Old content</summary>
@jakearchibald, @kjmcnee, please take a look. Other reviewers also appreciated.
Two main things to consider:
- Is this the behavior we want? I know @jakearchibald was skeptical about the "After the initial load" behavior, but I think it's better, and I believe @kjmcnee indicated that it's implementable. The alternative is to delay activation like we do with initial load, but that seems like a worse user experience.
- Is this explainer structure reasonable? I'm wondering if, e.g., we should move all discussion of …

Delay activation on initial loading; src="" changes reset portal BC

---

index.bs

Currently, a note suggests that closing the predecessor following a lack
of adoption fires unload handlers. This is not necessarily the case
given bfcache. We update this note and reference the issue for
discussing unload handlers.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/254.html" title="Last updated on Oct 9, 2020, 11:29 PM UTC (8327473)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/254/3c57d0d...8327473.html" title="Last updated on Oct 9, 2020, 11:29 PM UTC (8327473)">Diff</a>

Don't suggest that unload handlers would necessarily be run following activation

---

README.md
index.bs
security-and-privacy-questionnaire.md

Follows https://github.com/jeremyroman/alternate-loading-modes/pull/5.
The only intentional normative change here is that we now respect `prefetch-src` and use it as a fallback for `portal-src`.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/255.html" title="Last updated on Oct 30, 2020, 4:04 PM UTC (de6f119)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/255/3c57d0d...de6f119.html" title="Last updated on Oct 30, 2020, 4:04 PM UTC (de6f119)">Diff</a>

Rebase portals explainer on prerendering explainers

---

README.md

The gh-pages branch no longer has has any of this content so the links lead to 404

Fix README links to alternate-loading-mode

---

README.md

We expand on how portals affect session history and how reverse
transitions may be performed in the presence of bfcache and portal
adoption.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/256.html" title="Last updated on Nov 2, 2020, 3:40 PM UTC (cf8c35b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/256/3c57d0d...cf8c35b.html" title="Last updated on Nov 2, 2020, 3:40 PM UTC (cf8c35b)">Diff</a>

Add advanced session history integration to explainer

---

index.bs

It "must only appear on constructor operations":
https://html.spec.whatwg.org/#htmlconstructor
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/portals/pull/265.html" title="Last updated on Apr 19, 2021, 9:40 AM UTC (18ef638)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/265/0155437...foolip:18ef638.html" title="Last updated on Apr 19, 2021, 9:40 AM UTC (18ef638)">Diff</a>

Fix the use of [HTMLConstructor] extended attribute

---

index.bs

Also fixes a couple build errors on newer versions of Bikeshed.
(This is part of a larger project to clean up Googler and ex-Googler editors to make sure they're actively maintaining the specs they're listed as editing.)
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/279.html" title="Last updated on May 2, 2022, 3:58 PM UTC (ad26699)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/279/2f6c06e...ad26699.html" title="Last updated on May 2, 2022, 3:58 PM UTC (ad26699)">Diff</a>

Remove Lucas as editor
