WICG/portals

- explainer.md
> Tentative details for the news aggregator scenario

- explainer.md
> Allow activate to pass data

- explainer.md
Address issue #2:
- Third party cookie blocking
- Double keys storage
> Additional privacy points

- design-discussion.md
> GDPR considerations

- design-discussion.md
> Clarify behavior of portals and the session history.

- design-discussion.md
> Iframes shouldn't be allowed to create portals.

- index.bs
- index.html
This is a first pass at formalizing the portals work into a specification. There's still some stuff left out here to avoid making this PR any bigger. It's largely noted either in inline issues in the spec or existing GitHub issues.
Preview: https://rawgit.com/jeremyroman/portals/spec-draft/index.html
> Spec draft

- explainer.md
Trying to address some of the questions we've gotten so far. This is a little verbose; I'm not sure how to clarify or reduce it, though. I'd also appreciate more input on why `<portal>` is a good idea (or conversely, why it isn't).
Preview: https://github.com/jeremyroman/portals/blob/faqs/explainer.md
> Answer some frequently asked questions in the explainer.

- index.bs
> Modernize event construction and include required [Constructor].

- index.bs
> Fix usage of StructuredDeserializeWithTransfer.

- index.bs
> Link to global object realm when accessing via a Window object.

- index.bs
> Make portal states strings.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/102.html" title="Last updated on Apr 23, 2019, 8:05 PM UTC (35e9f3f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/102/2356368...jeremyroman:35e9f3f.html" title="Last updated on Apr 23, 2019, 8:05 PM UTC (35e9f3f)">Diff</a>
> Update WPT test references.

- index.bs
Resolves #85.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/101.html" title="Last updated on Apr 23, 2019, 8:13 PM UTC (f336965)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/101/4c40482...jeremyroman:f336965.html" title="Last updated on Apr 23, 2019, 8:13 PM UTC (f336965)">Diff</a>
> Various minor improvements to description of window.portalHost getter.

- index.bs
> Adopt the spec concept of 'browsing-context connected' to simplify insertion steps.

- index.bs
Just a heads up that this is a CG-Draft, not an W3C Editor's draft 🙏
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/121.html" title="Last updated on May 11, 2019, 11:44 AM UTC (d6e6aec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/121/adff395...d6e6aec.html" title="Last updated on May 11, 2019, 11:44 AM UTC (d6e6aec)">Diff</a>
> editorial: Use CG-Draft status

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/134.html" title="Last updated on May 24, 2019, 4:00 PM UTC (ba28f5b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/134/e0d59c4...jeremyroman:ba28f5b.html" title="Last updated on May 24, 2019, 4:00 PM UTC (ba28f5b)">Diff</a>
> Add a code example to resolve #70.

- index.bs
Resolves #78.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/136.html" title="Last updated on May 27, 2019, 7:43 PM UTC (35d9ef2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/136/8070b25...jeremyroman:35d9ef2.html" title="Last updated on May 27, 2019, 7:43 PM UTC (35d9ef2)">Diff</a>
> Support referrerpolicy content attribute on <portal>.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/144.html" title="Last updated on Jun 4, 2019, 8:07 PM UTC (cd2adc7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/144/af8c021...jeremyroman:cd2adc7.html" title="Last updated on Jun 4, 2019, 8:07 PM UTC (cd2adc7)">Diff</a>
> Update WPT cross-references.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/149.html" title="Last updated on Jun 11, 2019, 7:55 PM UTC (98bfa5f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/149/432c361...jeremyroman:98bfa5f.html" title="Last updated on Jun 11, 2019, 7:55 PM UTC (98bfa5f)">Diff</a>
> Throw a SyntaxError if an invalid URL is passed to postMessage.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/152.html" title="Last updated on Jul 3, 2019, 3:39 PM UTC (0cb64d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/152/de86b69...jeremyroman:0cb64d8.html" title="Last updated on Jul 3, 2019, 3:39 PM UTC (0cb64d8)">Diff</a>
> Fix two name references.

- demos/portal-embed-demo/package-lock.json
See https://github.com/WICG/portals/network/alert/demos/portal-embed-demo/package-lock.json/lodash/open.
Verified that the server still starts.
> Run 'npm audit fix' to resolve GitHub security alert.

- demos/portal-embed-demo/view/ttt.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wicg/portals/164)
> chore(typo): audio-controllercontroller -> audio-controller

- demos/portal-embed-demo/package-lock.json
- demos/portal-embed-demo/package.json
Resolves remaining security alerts against this repository.
> update npm dependencies to resolve security issues

- index.bs
Resolves #187
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/188.html" title="Last updated on May 4, 2020, 7:33 PM UTC (ec473b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/188/c67995d...ec473b5.html" title="Last updated on May 4, 2020, 7:33 PM UTC (ec473b5)">Diff</a>
> targetOrigin should be a USVString

- README.md
Critiques and suggestions welcome!
I'd also be interested in @jakearchibald's review (I just invited him to the repo so I can formally request it.)
> Expand on the differences between portals and iframes

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/201.html" title="Last updated on May 15, 2020, 9:06 PM UTC (c2c11cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/201/b34c7f3...c2c11cb.html" title="Last updated on May 15, 2020, 9:06 PM UTC (c2c11cb)">Diff</a>
> Add WPT pointers for CSP and XFO

- index.bs
This synchronizes the spec with the implementation and tests.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/200.html" title="Last updated on May 15, 2020, 9:03 PM UTC (ef8c303)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/200/b34c7f3...ef8c303.html" title="Last updated on May 15, 2020, 9:03 PM UTC (ef8c303)">Diff</a>
> Prevent portal creation in non-HTTP(S) schemes

- index.bs
Closes #67.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/202.html" title="Last updated on May 20, 2020, 8:36 PM UTC (0e7297b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/202/7200658...0e7297b.html" title="Last updated on May 20, 2020, 8:36 PM UTC (0e7297b)">Diff</a>
> Add a note about PortalActivateEvent's lack of ports

- README.md
Adds description of implemented default accessibility behaviour (default role and label) for portals.
> Add description of accessibility defaults

- index.bs
> Specify no portals in sandboxed documents

- index.bs
Closes #77 and helps with https://github.com/whatwg/html/issues/4980.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/222.html" title="Last updated on Jun 25, 2020, 9:37 PM UTC (66fe15e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/222/4f4929e...66fe15e.html" title="Last updated on Jun 25, 2020, 9:37 PM UTC (66fe15e)">Diff</a>
> Update all task-queuing to modern style

- README.md
Original PR text:
This proposal is a result of me going through the CSP specs and seeing what made sense. Much if it hasn't been discussed before, so review on this PR should also include high-level critiques of the proposal. I just thought it'd be simpler to discuss a concrete PR instead of an issue.
Update:
I've morphed this PR to cover CSP, document policy, and sandboxing all together, as there are cross-cutting concerns.
> Explain relation to CSP, document policy, and sandboxing

- README.md
- security-and-privacy-questionnaire.md
This is basically consolidating and linking to information that exists elsewhere.
> Flesh out security and privacy considerations

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/nschonni/portals/pull/261.html" title="Last updated on Feb 13, 2021, 9:07 PM UTC (104e2ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/261/1822f73...nschonni:104e2ea.html" title="Last updated on Feb 13, 2021, 9:07 PM UTC (104e2ea)">Diff</a>
> fix: Percent not allowed on width attribute

- index.bs
Follows https://github.com/whatwg/html/pull/3414.
Don't merge until that has merged and has had some time to make its way into linking databases.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/portals/pull/273.html" title="Last updated on Jul 27, 2021, 8:24 PM UTC (c73b345)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/portals/273/66aedaa...c73b345.html" title="Last updated on Jul 27, 2021, 8:24 PM UTC (c73b345)">Diff</a>
> Update PostMessageOptions → StructuredSerializeOptions
